-- Alias / handoff: a migration unificada vive em:
--   supabase/migrations/20260711_roles_agenda_outbox.sql
-- Cole o conteúdo desse arquivo no SQL Editor do Supabase.
-- Depois: NOTIFY pgrst, 'reload schema';
